/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/partners': typeof PartnersRoute
}
export interface FileRoutesByTo {
  '/partners': typeof PartnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/partners': typeof PartnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/partners'
  fileRoutesByTo: FileRoutesByTo
  to: '/partners'
  id: '__root__' | '/partners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PartnersRoute: typeof PartnersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PartnersRoute: PartnersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
